openapi: 3.2.0
info:
  title: PhotonIQ HyperSearch Models API
  description: API documentation for the PhotonIQ HyperSearch service
  version: 1.2.0
tags:
- name: Models
paths:
  /api/hss/v1/models:
    get:
      tags:
      - Models
      summary: Get models
      operationId: getModels
      responses:
        '200':
          description: Successfully returned list of models.
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Model'
                type: array
                title: Response Getmodels
      security:
      - APIKeyHeader: []
components:
  schemas:
    Model:
      properties:
        name:
          type: string
          title: Name
          description: The name of the model.
          examples:
          - sentence-transformers/all-MiniLM-L6-v2
        type:
          type: string
          title: Type
          description: The type of the model.
          examples:
          - sentence-transformers
        dimensions:
          type: integer
          title: Dimensions
          description: The dimensions of the model.
          examples:
          - 384
      type: object
      required:
      - name
      - type
      - dimensions
      title: Model
  securitySchemes:
    APIKeyHeader:
      type: apiKey
      in: header
      name: Authorization
